[package]
name = "csme-rs"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-lzma = "0.5.1"
hex = "0.4.3"
sha2 = "0.9.8"

[[bin]]
name = "parse-image"
path = "bin/parse-image.rs"

